version: '3.8'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_ADMIN_DATABASE}
    env_file:
      - ./.env
    ports:
      - 27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/entrypoint/:/docker-entrypoint-initdb.d/:ro
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
        ME_CONFIG_MONGODB_SERVER: mongodb
        ME_CONFIG_MONGODB_ENABLE_ADMIN: true
        ME_CONFIG_MONGODB_AUTH_DATABASE: ${MONGO_ADMIN_DATABASE}
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
        ME_CONFIG_BASICAUTH_USERNAME: ${ME_BASICAUTH_USERNAME:-mongo}
        ME_CONFIG_BASICAUTH_PASSWORD: ${ME_BASICAUTH_PASSWORD:-mongo}
    volumes:
      - ./mongodb/data:/data/db
    depends_on:
      - mongodb
    ports:
      - ${ME_HOST_PORT:-8081}:8081
    healthcheck:
      test:  wget --quiet --tries=3 --spider http://${MONGO_USER}:${MONGO_PASSWORD}@mongo-express:8081 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped